apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: CHMURA
            - name: POSTGRES_PASSWORD
              value: CHMURAPassword
            - name: POSTGRES_USER
              value: CHMURAUser
          image: postgres:13.14-bullseye
          name: database
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
