version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./chmura-front/
    ports:
      - "8082:8082"
    depends_on:
        - backend
  backend:
    build: ./Backend/Chmura/
    container_name: backend
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:13.14-bullseye
    restart: always
    environment:
      POSTGRES_DB: CHMURA
      POSTGRES_USER: CHMURAUser
      POSTGRES_PASSWORD: CHMURAPassword
    ports:
      - "5432:5432"
