apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: systemychmurowe-frontend:latest # rollo53/frontend:1.1
          name: frontend
          ports:
            - containerPort: 8082
          env:
          - name: VITE_BACKEND_URL
            value: "http://127.0.0.1:8080"
          resources: {}
      restartPolicy: Always
status: {}
