- hosts: all
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Install dotnet
      ansible.builtin.shell:
        cmd: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get install apt-transport-https -y
            sudo apt-get update -y
            sudo apt-get install dotnet-sdk-2.2 -y

    # - name: Install .NET Core SDK
    #   pacman:
    #     name: dotnet-sdk
    #     state: present

    - name: Clone project repository
      ansible.builtin.git:
        dest: ~/SystemyChmurowe
        repo: https://github.com/RoIIo/SystemyChmurowe.git
        force: yes

    - name: Delete existing 'backend' directory if it exists
      ansible.builtin.file:
        path: ~/backend
        state: absent

    - name: Move project to 'backend' directory
      ansible.builtin.shell: mv ~/SystemyChmurowe/Backend ~/backend

    - name: Ensure 'backend' directory exists
      ansible.builtin.file:
        path: ~/backend
        state: directory

    - name: Build the .NET Web API project
      shell: dotnet build ~/backend

    - name: Run the .NET Web API project
      shell: dotnet run ~/backend
