- hosts: all
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

    - name: Install python
      ansible.builtin.apt:
        name: python3-apt
        state: present
        update_cache: yes

    - name: Install psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: present
        update_cache: yes

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - postgresql
        - postgresql-contrib

    - name: Set password
      ansible.builtin.command: sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'CHMURAPassword';"
    # - name: Create user
    #   ansible.builtin.command: sudo -u postgres createuser CHMURAUser
    # - name: Set password
    #   ansible.builtin.command: sudo -u postgres psql -c "ALTER USER CHMURAUser PASSWORD 'PASSWORDUser';"

    # - name: Backup postgresql.conf
    #   ansible.builtin.copy:
    #     src: /etc/postgresql/15/main/postgresql.conf
    #     dest: /etc/postgresql/15/main/postgresql.conf.bak
    #     remote_src: yes

    # - name: Allow connections from all IPs
    #   lineinfile:
    #     path: /etc/postgresql/15/main/postgresql.conf
    #     regexp: "^#?listen_addresses"
    #     line: "listen_addresses = '*'"

    # - name: Backup pg_hba.conf
    #   ansible.builtin.copy:
    #     src: /etc/postgresql/15/main/pg_hba.conf
    #     dest: /etc/postgresql/15/main/pg_hba.conf.bak
    #     remote_src: yes

    # - name: Allow specific IP in pg_hba.conf
    #   lineinfile:
    #     path: /etc/postgresql/15/main/pg_hba.conf
    #     line: "host all all 192.168.50.5/32 md5"

    - name: Create PostgreSQL database
      postgresql_db:
        name: CHMURA
        owner: postgres
        login_password: CHMURAPassword
        state: present

    - name: Restart service
      ansible.builtin.service:
        name: postgresql
        state: restarted
