- hosts: all
  become: yes

  tasks:
    - name: Update keyring
      community.general.pacman:
        name: archlinux-keyring
        state: latest
        update_cache: yes

    - name: Update system using pacman
      community.general.pacman:
        update_cache: yes
        upgrade: yes
        force: yes
    - name: Install python
      community.general.pacman:
        name: python
        state: latest

    - name: Ensure PostgreSQL directory exists with correct permissions
      ansible.builtin.file:
        path: /var/lib/postgres/data
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Install PostgreSQL
      pacman:
        name: postgresql
        state: present  # Ensure PostgreSQL is installed

    - name: Initialize PostgreSQL database
      become_user: postgres
      command: /usr/bin/initdb -D /var/lib/postgres/data
      become: yes

    - name: Start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: yes
        become: yes

    - name: Create PostgreSQL user
      postgresql_user:
        db: postgres
        name: CHMURAUser
        password: PASSWORDUser
        state: present

    - name: Create PostgreSQL database
      postgresql_db:
        name: CHMURA
        owner: CHMURAUser
        state: present
