- hosts: all
  become: yes

  tasks:
   
    - name: Update system using apt
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        force: yes
    - name: Install psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: latest
    - name: Install python
      ansible.builtin.apt:
        name: python3-apt
        state: latest

    - name: Ensure PostgreSQL directory exists with correct permissions
      ansible.builtin.file:
        path: /var/lib/postgres/data
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - postgresql
        - postgresql-contrib

    # - name: Initialize PostgreSQL database
    #   become_user: postgres
    #   command: /usr/bin/initdb -D /var/lib/postgres/data
    #   become: yes

    # - name: Start PostgreSQL service
    #   systemd:
    #     name: postgresql
    #     state: started
    #     enabled: yes

    # - name: Create PostgreSQL userr
    #   postgresql_user:
    #     # db: CHMURA
    #     name: CHMURAUser
    #     password: PASSWORDUser
    #     state: present

    # - name: Create PostgreSQL database
    #   postgresql_db:
    #     name: CHMURA
    #     owner: CHMURAUser
    #     state: present

    - name: Create a PostgreSQL database user
      postgresql_user: name=CHMURAUser password=PASSWORDUser role_attr_flags=CREATEDB state=present
      become: yes
      become_user: postgres
      become_method: sudo

    - name: Create  database
      become: yes
      become_user: postgres
      postgresql_db:
        name: CHMURA
        encoding: UTF-8
