- hosts: all
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

    # - name: apache is installed
    #   ansible.builtin.apt:
    #     name: apache
    #     state: present
    #     update_cache: yes

    - name: httpd service is enabled
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Npm is installed
      ansible.builtin.apt:
        name: npm
        state: latest
        update_cache: yes



    - name: Install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: latest
        update_cache: yes
    - name: Install pm2 globally
      ansible.builtin.command:
        cmd: npm install pm2 -g
      
    - name: Install python
      ansible.builtin.apt:
        name: python
        state: latest

    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: latest

    - name: Clone project repository
      ansible.builtin.git:
        dest: ~/SystemyChmurowe
        repo: https://github.com/RoIIo/SystemyChmurowe.git
        force: yes

    - name: Delete existing 'front' directory if it exists
      ansible.builtin.file:
        path: ~/front
        state: absent

    - name: Move project to 'front' directory
      ansible.builtin.shell: mv ~/SystemyChmurowe/chmura-front ~/front

    - name: Ensure 'front' directory exists
      ansible.builtin.file:
        path: ~/front
        state: directory

    - name: Install packages
      ansible.builtin.shell: npm install
      args:
        chdir: ~/front
    - name: Build project
      ansible.builtin.shell: npm run build
      args:
        chdir: ~/front

    - name: Fix broken packages
      ansible.builtin.command:
        cmd: sudo apt --fix-broken install

    - name: Start the application
      ansible.builtin.command:
        cmd: pm2 start npm --name "my-app" -- run start
        chdir: ~/front

    - name: Front is ready
      debug:
        msg: "Front is ready"